import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "rooks-and-knights",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className='h-screen bg-gray-900'>
				<Navbar/>
				{children}
				<Footer/>
				</body>
		</html>
	);
}
