import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Rooks & Knights",
	description: "Generated by create next app",
//  // Note: in Next 13.4+ you can also specify:
  icons: {
    icon: "/king.jpg",
  },
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className='flex flex-col min-h-screen bg-gray-900'>
				<Navbar/>
				{children}
				<Footer/>
				</body>
		</html>
	);
}
